
const translations={
  ar:{dir:'rtl',lang:'العربية',navServices:'الخدمات',navDoctor:'د. عمر',navCases:'قبل وبعد',navBooking:'الحجز',navContact:'تواصل معنا',navCTA:'احجز موعدك',heroEyebrow:'GAZZAR DENTAL CLINIC · LORAN ALEXANDRIA',heroTitle:'ابتسامتك تبدأ من هنا',heroLead:'تجميل أسنان، تقويم شفاف، زراعة، وفينيرز بتخطيط رقمي ونتائج طبيعية داخل عيادة راقية في لوران، الإسكندرية.',bookNow:'احجز موعدك',whatsapp:'تواصل واتساب',badgeTitle:'نتائج حقيقية',badgeText:'شاهد نماذج قبل وبعد من حالات العيادة.',t1:'تقنيات رقمية',t1d:'تخطيط دقيق ونتائج أكثر توقعًا',t2:'د. عمر الجزار',t2d:'10+ سنوات خبرة في التجميل والتقويم الشفاف',t3:'راحة وخصوصية',t3d:'تجربة زيارة هادئة ومنظمة',t4:'حجز سريع',t4d:'تحويل بيانات الحجز مباشرة للواتساب',servicesTitle:'خدماتنا المميزة',servicesLead:'كل خدمة معروضة بسعر بداية واضح، والتكلفة النهائية تتحدد بعد الكشف حسب حالة الأسنان وخطة العلاج.',whyTitle:'عيادة بتفاصيل راقية ونتائج موثقة',whyLead:'من أول الاستقبال وحتى غرفة الكشف، التجربة مبنية على الراحة، النظافة، والتخطيط الدقيق.',doctorTitle:'د. عمر الجزار',doctorLead:'متخصص في التقويم الشفاف وتجميل الأسنان، ويركز على تقديم ابتسامات طبيعية مناسبة لشكل الوجه باستخدام تقنيات رقمية متقدمة.',bookingTitle:'احجز موعدك الآن',bookingLead:'املأ بياناتك، وبعد الضغط على تأكيد الحجز سيتم فتح واتساب تلقائيًا برسالة كاملة بالاسم، الخدمة، التاريخ والساعة.',reviewsTitle:'تقييمات Google',reviewsLead:'لم يتم وضع تقييمات نصية غير موثقة. يمكنك فتح صفحة خرائط Google لمراجعة التقييمات الحقيقية للعيادة مباشرة.',contactTitle:'زورونا في لوران',contactLead:'723 لوران، شارع أبوقير، أبراج فينيسيا وبنك QNB، أمام مدينة الأحلام – الإسكندرية.'},
  en:{dir:'ltr',lang:'English',navServices:'Services',navDoctor:'Dr. Omar',navCases:'Before & After',navBooking:'Booking',navContact:'Contact',navCTA:'Book Appointment',heroEyebrow:'GAZZAR DENTAL CLINIC · LORAN ALEXANDRIA',heroTitle:'Confident smiles start here',heroLead:'Cosmetic dentistry, clear aligners, implants and veneers with digital planning and natural-looking results in Loran, Alexandria.',bookNow:'Book Appointment',whatsapp:'WhatsApp',badgeTitle:'Real transformations',badgeText:'Explore selected before and after cases from the clinic.',t1:'Digital Dentistry',t1d:'Precise planning and predictable results',t2:'Dr. Omar El-Gazzar',t2d:'10+ years in cosmetic dentistry and clear aligners',t3:'Comfort & Privacy',t3d:'A calm and organized patient experience',t4:'Fast Booking',t4d:'Your booking details go directly to WhatsApp',servicesTitle:'Featured Treatments',servicesLead:'Each service includes a clear starting price. Final treatment cost is confirmed after examination and diagnosis.',whyTitle:'A refined clinic experience with documented results',whyLead:'From reception to treatment rooms, the experience is designed around comfort, cleanliness and precise planning.',doctorTitle:'Dr. Omar El-Gazzar',doctorLead:'Specialized in Clear Aligners and Cosmetic Dentistry, with a focus on natural smile transformations using advanced digital techniques.',bookingTitle:'Book your appointment',bookingLead:'Fill in your details, then tap confirm. WhatsApp will open automatically with your full booking message.',reviewsTitle:'Google Reviews',reviewsLead:'No unverified text reviews are displayed. Open Google Maps to view the real clinic reviews directly.',contactTitle:'Visit us in Loran',contactLead:'723 Loran, Abu Qir Street, Venicia Towers, next to QNB Bank, in front of Madinet El Ahlam – Alexandria.'}
};
const root=document.documentElement; const body=document.body;
function setLang(lang){const t=translations[lang];body.dir=t.dir;body.lang=lang;document.querySelectorAll('[data-t]').forEach(el=>{const k=el.getAttribute('data-t');if(t[k])el.innerHTML=t[k]});localStorage.setItem('gazzar-lang',lang)}
document.getElementById('langBtn')?.addEventListener('click',()=>setLang((localStorage.getItem('gazzar-lang')||'ar')==='ar'?'en':'ar'));
document.getElementById('menuBtn')?.addEventListener('click',()=>document.getElementById('navlinks')?.classList.toggle('open'));
setLang(localStorage.getItem('gazzar-lang')||'ar');
// Pre-fill service when clicking service button
Array.from(document.querySelectorAll('[data-service]')).forEach(a=>a.addEventListener('click',()=>{const s=document.getElementById('service'); if(s) s.value=a.dataset.service;}));
const form=document.getElementById('bookingForm');
form?.addEventListener('submit',e=>{e.preventDefault();
 const name=document.getElementById('patientName').value.trim();
 const phone=document.getElementById('patientPhone').value.trim();
 const service=document.getElementById('service').value;
 const date=document.getElementById('date').value;
 const time=document.getElementById('time').value;
 const notes=document.getElementById('notes').value.trim();
 const text=`حجز موعد جديد - GAZZAR Dental Clinic%0A%0Aالاسم: ${encodeURIComponent(name)}%0Aرقم المريض: ${encodeURIComponent(phone)}%0Aالخدمة المطلوبة: ${encodeURIComponent(service)}%0Aالتاريخ المفضل: ${encodeURIComponent(date)}%0Aالساعة المفضلة: ${encodeURIComponent(time)}%0Aملاحظات: ${encodeURIComponent(notes||'لا يوجد')}%0A%0Aتم إرسال البيانات من فورم الموقع.`;
 window.open(`https://wa.me/201221753277?text=${text}`,'_blank');
});
